// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtOdhchYN_-dQLgl-I1zIocBcMHMYtLiI',
    appId: '1:19675674756:web:3191267f9ec9648341aad1',
    messagingSenderId: '19675674756',
    projectId: 'chat-a1127',
    authDomain: 'chat-a1127.firebaseapp.com',
    storageBucket: 'chat-a1127.appspot.com',
    measurementId: 'G-7P3B9DGR0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDINb5eS73M7P-sgrpiSzVdJVS8lVgyy_4',
    appId: '1:19675674756:android:b73255135548cc4b41aad1',
    messagingSenderId: '19675674756',
    projectId: 'chat-a1127',
    storageBucket: 'chat-a1127.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPNw7OXcdJ_dR2jtiy6ZH7OHwPlRYtjl8',
    appId: '1:19675674756:ios:1740caa75f445d1241aad1',
    messagingSenderId: '19675674756',
    projectId: 'chat-a1127',
    storageBucket: 'chat-a1127.appspot.com',
    iosBundleId: 'com.example.chatApp2',
  );
}
